---
title: "HW1"
author: "Group 34"
output: 
  pdf_document:
    number_sections: yes
    toc: yes
    toc_depth: '4'
  html_document:
    code_folding: show
    highlight: haddock
    number_sections: yes
    theme: lumen
    toc: yes
    toc_depth: 4
    toc_float: yes
  word_document:
    toc: yes
    toc_depth: '4'
urlcolor: blue
editor_options: 
  chunk_output_type: inline
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo=TRUE,fig.width = 8, fig.height=4)
options(scipen=0,digits=3)
if(!require('pacman'))
{
  install.packages('pacman')
}
pacman::p_load(ggplot2, dplyr, tidyverse, gridExtra, ggrepel, plotly, skimr, tidytext, readxl)
getwd()
```


```{r data wrangling, echo = FALSE, warning = FALSE}
bb <- read.csv("baseball.csv", header=T, stringsAsFactors =F)
names(bb)
head(bb)
```


```{r}
bb <-bb %>% arrange(team, year)
bb$number<-bb$win_num/bb$win_pct #making sure that number of games is constant
bb[1:50,]
head(bb)
```
### 4.1 (A)

The utility function is better approximated by log or sqrt, than by a straight line, so log is more appropriate here.


### 4.1 (B)

```{r}
bb$diff_one_year <- NA
bb$diff_log_one_year <- NA
bb$diff_percent_win_num <- NA

bb$diff_one_year <- bb$payroll - lag(bb$payroll) 
bb$diff_log_one_year <- exp(log(bb$payroll)-log(lag(bb$payroll)))
bb$diff_percent_win_num <- (bb$win_num/lag(bb$win_num)-1)*100

bb[1:50,]
```

### 4.1 (C)

```{r}

bb_new <- bb %>% select(team, year, diff_log_one_year, win_num, payroll)
bb_new[1:50,]

```


```{r}
bb_new <- bb_new %>% mutate(diff_log_one_year=ifelse(team==lag(team),diff_log_one_year,NA))

bb_new[1:50,]
```

```{r}
bb_new <- bb_new[complete.cases(bb_new), ]
bb_new[1:50,]
```

### 4.2

```{r}
b<-bb_new %>% select(team, year, win_num, payroll) %>% filter (year==2010 | year == 2014)
b[1:50,]
```

```{r}
b$five_year_win_inc=(b$win_num/lag(b$win_num)-1)*100
b$five_year_log_pay_inc=exp(log(b$payroll)-lag(log(b$payroll)))
b<- b %>% filter(year==2014)
b<- b %>% select(team, five_year_win_inc, five_year_log_pay_inc)
b[1:50,]
```

### 4.2 (A)
```{r}
b <- b[complete.cases(b),]
b <- b %>% arrange(-five_year_log_pay_inc)
b[1:5,]
```

### 4.2 (B)
```{r}
b <- b %>% arrange(-five_year_win_inc)
b[1:5,]
```
### 4.3
```{r}
b_three<- bb %>% select(team, year, payroll, diff_log_one_year, diff_percent_win_num)
b_three <- b_three %>% filter (year>1998)
bb[1:50,]
b_three[1:50,]
```
```{r}
b_three %>%
  ggplot(aes(x=diff_log_one_year,y=diff_percent_win_num))+
  geom_point(aes(color=team), size =1)+
  geom_smooth(method="lm", formula = y ~ x, se=F, color="red")+
  geom_hline(aes(yintercept=mean(diff_percent_win_num)), color="blue")+
  theme_bw()

b_three %>%
  ggplot(aes(x=diff_log_one_year,y=diff_percent_win_num))+
  geom_point(aes(color=year), size =1)+
  geom_smooth(method = "lm", formula = y ~ x, se = F,color = "red") + 
  geom_hline(aes(yintercept=mean(diff_percent_win_num)), color="blue")+
  theme_bw()
```

```{r}
b_three %>%
  ggplot(aes(x=diff_log_one_year, y=diff_percent_win_num, group=team, color=team))+
  geom_point()+
  geom_smooth(method="lm", formula = y~x, se=F, color="red")+
  facet_wrap(~team)+
  theme_bw()+
  theme(legend.position = "none")

b_three %>%
  ggplot(aes(x=diff_log_one_year, y=diff_percent_win_num, group = year, color=team)) +
  geom_point()+
  geom_smooth(method="lm", formula=y~x, se=F,color = "red")+
  facet_wrap(~year) + 
  theme_bw() +
  theme(legend.position = 0)

p <- b_three %>%
  ggplot(aes(x=diff_log_one_year, y=diff_percent_win_num, color=team, frame=year))+ theme(legend.position = 0) +
  geom_point()+
  geom_smooth(method="lm", formula = y~x, se=F, color="red")+
  theme_bw()
  
ggplotly(p)
```

### 4.4
```{r}
b_three %>%
  ggplot(aes(x=payroll, y=diff_percent_win_num, group=team, color=team))+
  geom_point()+
  geom_smooth(method="lm", formula = y~x, se=F, color="red")+
  facet_wrap(~team)+
  theme_bw()+
  theme(legend.position = "none")

b_three %>%
  ggplot(aes(x=payroll, y=diff_percent_win_num, group = year, color=team)) +
  geom_point()+
  geom_smooth(method="lm", formula=y~x, se=F,color = "red")+
  facet_wrap(~year) + 
  theme_bw() +
  theme(legend.position = 0)

p <- b_three %>%
  ggplot(aes(x=payroll, y=diff_percent_win_num, color=team, frame=year))+ theme(legend.position = 0) +
  geom_point()+
  geom_smooth(method="lm", formula = y~x, se=F, color="red")+
  theme_bw()
  
ggplotly(p)

```

### 4.4
On comparing these graphs with those from the prior chunk, we note that the regression slopes are flatter here, indicating that the former is better at explaining performance.